### ISSUE TITLE
Not properly encoded asterisks result in error 32 "Could not authenticate you."

### ISSUE THREAD

**Issue by mdom** [Grinnz/Mojo-WebService-Twitter#2]
Every time i use an asterisk in a tweet, i get the response error 32 "Could not authenticate you." Maybe it's the same problem as described in https://github.com/sferik/twitter/issues/677#issuecomment-586599827?

**Comment by Grinnz** [comment]
https://github.com/Grinnz/Mojo-WebService-Twitter/commit/085ceef16e5de63b44fbb0fc9b15ef6bd58b0638 should hopefully resolve this. Thanks for the report!

**Comment by mdom** [comment]
Great, thanks! Works like a charme!

Cheers, Mario
